import CIcon from '@coreui/icons-react';
import {
  cilSpeedometer,
  cilPeople,
  cilLayers,
  cilChart,
  cilMoney,
  cilSettings,
  cilList,
  cilDescription,
  cilUser,
  cilCalendar,
  cilSearch,
  cilTask,
  cilChartPie,
  cilChartLine,
  cilEnvelopeClosed,
  cilChatBubble,
  cilPhone,
  cilMediaPlay,
} from '@coreui/icons';
import { CNavItem, CNavGroup } from '@coreui/react';

const _nav = [
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
  },
  {
    component: CNavGroup,
    name: 'Operativita',
    to: '/operativita',
    icon: <CIcon icon={cilLayers} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Agenda',
        to: '/calendar',
        icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Pazienti',
        to: '/pazienti',
        icon: <CIcon icon={cilUser} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Richiami',
        to: '/pazienti/richiami',
        icon: <CIcon icon={cilPhone} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Slot liberi',
        to: '/richiami/slot-liberi',
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Lavorazioni',
        to: '/works',
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Task',
        to: '/tasks',
        icon: <CIcon icon={cilTask} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Todo',
        to: '/todos',
        icon: <CIcon icon={cilTask} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Matrice Eisenhower',
        to: '/eisenhower',
        icon: <CIcon icon={cilChart} customClassName="nav-icon" />,
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Amministrazione',
    to: '/amministrazione',
    icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Fornitori',
        to: '/fornitori',
        icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Classificazione fornitori',
        to: '/fornitori/classificazione',
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Materiali',
        to: '/materiali',
        icon: <CIcon icon={cilLayers} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Ricerca materiali',
        to: '/materiali/ricerca',
        icon: <CIcon icon={cilSearch} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Spese',
        to: '/spese',
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Conti',
        to: '/conti',
        icon: <CIcon icon={cilMoney} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Collaboratori',
        to: '/collaboratori',
        icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Comunicazioni',
    to: '/comunicazioni',
    icon: <CIcon icon={cilChatBubble} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Email',
        to: '/email',
        icon: <CIcon icon={cilEnvelopeClosed} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Bot WhatsApp',
        to: '/bot',
        icon: <CIcon icon={cilChatBubble} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Template',
        to: '/settings/template',
        icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Automazioni',
        to: '/settings/automazioni',
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Simulazione flussi',
        to: '/simulation',
        icon: <CIcon icon={cilMediaPlay} customClassName="nav-icon" />,
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Sanitario',
    to: '/sanitario',
    icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Ricetta elettronica',
        to: '/ricetta',
        icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Test ricette',
        to: '/ricetta/test',
        icon: <CIcon icon={cilList} customClassName="nav-icon" />,
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Analisi e controllo',
    to: '/analisi',
    icon: <CIcon icon={cilChartPie} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Economics',
        to: '/economics',
        icon: <CIcon icon={cilChartPie} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Analisi comparativa',
        to: '/economics/comparativa',
        icon: <CIcon icon={cilChartLine} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Centro di costo',
        to: '/economics/centro-costo',
        icon: <CIcon icon={cilChart} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Monitor quaderno',
        to: '/settings/monitor-prestazioni',
        icon: <CIcon icon={cilChart} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'SEO',
        to: '/settings/seo',
        icon: <CIcon icon={cilSearch} customClassName="nav-icon" />,
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Sistema',
    to: '/sistema',
    icon: <CIcon icon={cilSettings} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Utenti',
        to: '/users',
        icon: <CIcon icon={cilUser} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Scheduler',
        to: '/settings/scheduler',
        icon: <CIcon icon={cilSettings} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Impostazioni calendario',
        to: '/settings/calendar',
        icon: <CIcon icon={cilCalendar} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'WhatsApp reminder',
        to: '/settings/evolution',
        icon: <CIcon icon={cilPhone} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Migrazione materiali',
        to: '/materiali/migrazione',
        icon: <CIcon icon={cilSettings} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Providers',
        to: '/providers',
        icon: <CIcon icon={cilPeople} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Steps template',
        to: '/steps',
        icon: <CIcon icon={cilSettings} customClassName="nav-icon" />,
      },
      {
        component: CNavItem,
        name: 'Test componenti',
        to: '/test',
        icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
      },
    ],
  },
];

export default _nav;
