import React, { useState, useMemo } from 'react';
import { 
  CTable, 
  CTableHead, 
  CTableRow, 
  CTableHeaderCell, 
  CTableBody, 
  CTableDataCell,
  CFormInput,
  CFormSelect,
  CPagination,
  CPaginationItem,
  CSpinner,
  CDropdown,
  CDropdownToggle,
  CDropdownMenu,
  CDropdownItem,
  CFormCheck
} from '@coreui/react';

import './DataTable.css';

export interface DataTableColumn<T> {
  key: keyof T;
  label: string;
  sortable?: boolean;
  render?: (value: any, item: T) => React.ReactNode;
  width?: string;
  defaultVisible?: boolean; // Colonna visibile di default
  order?: number; // Ordine di visualizzazione
}

interface DataTableProps<T> {
  data: T[];
  columns: DataTableColumn<T>[];
  loading?: boolean;
  error?: string | null;
  searchable?: boolean;
  searchPlaceholder?: string;
  pageSize?: number;
  pageSizeOptions?: number[];
  className?: string;
  tableId?: string; // ID univoco per salvare configurazione colonne
  autoDetectColumns?: boolean; // Auto-genera colonne da dati
}

type SortDirection = 'asc' | 'desc' | null;

const DataTable = <T extends Record<string, any>>({
  data,
  columns: initialColumns,
  loading = false,
  error = null,
  searchable = true,
  searchPlaceholder = "Cerca...",
  pageSize = 10,
  pageSizeOptions = [10, 20, 50, 100],
  className = "",
  tableId = "default-table",
  autoDetectColumns = false
}: DataTableProps<T>) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(pageSize);
  const [sortColumn, setSortColumn] = useState<keyof T | null>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>(null);
  
  // Auto-genera colonne se richiesto
  const autoGeneratedColumns = useMemo((): DataTableColumn<T>[] => {
    if (!autoDetectColumns || data.length === 0) return [];
    
    const firstItem = data[0];
    const detectedColumns: DataTableColumn<T>[] = [];
    
    Object.keys(firstItem).forEach((key, index) => {
      // Escludi colonne che sono già definite manualmente
      if (!initialColumns.some(col => col.key === key)) {
        detectedColumns.push({
          key: key as keyof T,
          label: key.charAt(0).toUpperCase() + key.slice(1).replace(/_/g, ' '),
          sortable: true,
          defaultVisible: false,
          order: 1000 + index, // Ordine alto per metterle in fondo
          render: (value) => {
            // Gestione speciale per date
            if (key.includes('data') && value) {
              try {
                return new Date(value).toLocaleDateString('it-IT');
              } catch {
                return String(value);
              }
            }
            return String(value ?? '-');
          }
        });
      }
    });
    
    return detectedColumns;
  }, [data, initialColumns, autoDetectColumns]);
  
  // Combina colonne manuali e auto-generate
  const allColumns = useMemo(() => {
    return [...initialColumns, ...autoGeneratedColumns].sort((a, b) => {
      const orderA = a.order ?? 100;
      const orderB = b.order ?? 100;
      return orderA - orderB;
    });
  }, [initialColumns, autoGeneratedColumns]);
  
  // Carica configurazione colonne salvata
  const loadColumnConfig = () => {
    if (!tableId) return { visible: new Set<keyof T>(), order: allColumns };
    
    try {
      const saved = localStorage.getItem(`table-config-${tableId}`);
      if (saved) {
        const config = JSON.parse(saved);
        const visibleSet = new Set<keyof T>(config.visibleColumns);
        
        
        // Ordina colonne secondo configurazione salvata
        const orderedColumns: DataTableColumn<T>[] = [];
        const unorderedColumns: DataTableColumn<T>[] = [];
        
        // Prima aggiungi le colonne nell'ordine salvato
        config.columnOrder.forEach((savedKey: string) => {
          const column = allColumns.find(col => String(col.key) === savedKey);
          if (column) {
            orderedColumns.push(column);
          }
        });
        
        // Poi aggiungi eventuali nuove colonne non presenti nell'ordine salvato
        allColumns.forEach(col => {
          if (!config.columnOrder.includes(String(col.key))) {
            unorderedColumns.push(col);
          }
        });
        
        const finalOrder = [...orderedColumns, ...unorderedColumns];
        
        return { visible: visibleSet, order: finalOrder };
      }
    } catch (error) {
      console.warn('Errore caricamento configurazione tabella:', error);
    }
    
    // Default: solo colonne con defaultVisible !== false
    const defaultVisible = new Set<keyof T>();
    allColumns.forEach(col => {
      if (col.defaultVisible !== false) {
        defaultVisible.add(col.key);
      }
    });
    
    return { visible: defaultVisible, order: allColumns };
  };
  
  // Salva configurazione colonne
  const saveColumnConfig = (visibleCols: Set<keyof T>, orderedCols: DataTableColumn<T>[]) => {
    if (!tableId) return;
    
    try {
      const config = {
        visibleColumns: Array.from(visibleCols),
        columnOrder: orderedCols.map(col => String(col.key))
      };
      localStorage.setItem(`table-config-${tableId}`, JSON.stringify(config));
    } catch (error) {
      console.warn('Errore salvataggio configurazione tabella:', error);
    }
  };
  
  // Stato configurazione colonne
  const [columnConfig, setColumnConfig] = useState(() => loadColumnConfig());
  const [visibleColumns, setVisibleColumns] = useState(columnConfig.visible);
  const [orderedColumns, setOrderedColumns] = useState(columnConfig.order);
  
  // Aggiorna quando cambiano le colonne
  React.useEffect(() => {
    const newConfig = loadColumnConfig();
    setVisibleColumns(newConfig.visible);
    setOrderedColumns(newConfig.order);
  }, [allColumns.length, tableId]);

  const toggleColumn = (columnKey: keyof T) => {
    const newVisible = new Set(visibleColumns);
    if (newVisible.has(columnKey)) {
      newVisible.delete(columnKey);
    } else {
      newVisible.add(columnKey);
    }
    setVisibleColumns(newVisible);
    saveColumnConfig(newVisible, orderedColumns);
  };
  
  // Sposta colonna (drag & drop) - lavora con l'ordine completo delle colonne
  const moveColumn = (fromVisibleIndex: number, toVisibleIndex: number) => {
    const visibleCols = orderedColumns.filter(col => visibleColumns.has(col.key));
    const movedColumn = visibleCols[fromVisibleIndex];
    const targetColumn = visibleCols[toVisibleIndex];
    
    if (!movedColumn || !targetColumn) return;
    
    // Trova gli indici nel array completo delle colonne
    const fromFullIndex = orderedColumns.findIndex(col => col.key === movedColumn.key);
    const toFullIndex = orderedColumns.findIndex(col => col.key === targetColumn.key);
    
    if (fromFullIndex === -1 || toFullIndex === -1) return;
    
    // Crea nuovo ordine completo
    const newOrder = [...orderedColumns];
    const [removed] = newOrder.splice(fromFullIndex, 1);
    newOrder.splice(toFullIndex, 0, removed);
    
    setOrderedColumns(newOrder);
    saveColumnConfig(visibleColumns, newOrder);
  };

  // Filtra solo le colonne visibili
  const visibleColumnsData = orderedColumns.filter(col => visibleColumns.has(col.key));

  // Filtra i dati in base alla ricerca
  const filteredData = useMemo(() => {
    if (!searchTerm.trim()) return data;
    
    const searchLower = searchTerm.toLowerCase().trim();
    return data.filter(item =>
      visibleColumnsData.some(column => {
        const value = item[column.key];
        if (value == null) return false;
        return String(value).toLowerCase().includes(searchLower);
      })
    );
  }, [data, searchTerm, visibleColumnsData]);

  // Ordina i dati
  const sortedData = useMemo(() => {
    if (!sortColumn || !sortDirection) return filteredData;

    return [...filteredData].sort((a, b) => {
      const aVal = a[sortColumn];
      const bVal = b[sortColumn];
      
      // Gestione valori null/undefined
      if (aVal == null && bVal == null) return 0;
      if (aVal == null) return sortDirection === 'asc' ? -1 : 1;
      if (bVal == null) return sortDirection === 'asc' ? 1 : -1;
      
      // Confronto valori
      let comparison = 0;
      if (typeof aVal === 'string' && typeof bVal === 'string') {
        comparison = aVal.localeCompare(bVal);
      } else if (typeof aVal === 'number' && typeof bVal === 'number') {
        comparison = aVal - bVal;
      } else {
        comparison = String(aVal).localeCompare(String(bVal));
      }
      
      return sortDirection === 'asc' ? comparison : -comparison;
    });
  }, [filteredData, sortColumn, sortDirection]);

  // Paginazione
  const totalItems = sortedData.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentData = sortedData.slice(startIndex, endIndex);

  // Gestione ordinamento
  const handleSort = (column: keyof T) => {
    const columnConfig = visibleColumnsData.find(col => col.key === column);
    if (!columnConfig?.sortable) return;

    if (sortColumn === column) {
      // Cicla: asc -> desc -> null
      if (sortDirection === 'asc') {
        setSortDirection('desc');
      } else if (sortDirection === 'desc') {
        setSortDirection(null);
        setSortColumn(null);
      }
    } else {
      setSortColumn(column);
      setSortDirection('asc');
    }
  };

  // Reset pagination quando cambiano filtri
  React.useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, itemsPerPage]);

  // Componente paginazione compatta (per header)
  const CompactPaginationComponent = () => {
    if (totalPages <= 1) return null;

    return (
      <div className="d-flex align-items-center gap-3">
        <div className="text-muted small">
          {startIndex + 1}-{Math.min(endIndex, totalItems)} di {totalItems}
        </div>
        
        <CPagination size="sm">
          <CPaginationItem
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(currentPage - 1)}
          >
            ‹
          </CPaginationItem>
          <CPaginationItem active>
            {currentPage}
          </CPaginationItem>
          <CPaginationItem
            disabled={currentPage === totalPages}
            onClick={() => setCurrentPage(currentPage + 1)}
          >
            ›
          </CPaginationItem>
        </CPagination>
        
        <div className="d-flex align-items-center gap-1">
          <span className="text-muted small">per pagina:</span>
          <CFormSelect
            size="sm"
            value={itemsPerPage}
            onChange={(e) => setItemsPerPage(Number(e.target.value))}
            style={{ width: '70px' }}
          >
            {pageSizeOptions.map(size => (
              <option key={size} value={size}>{size}</option>
            ))}
          </CFormSelect>
        </div>
      </div>
    );
  };

  // Componente paginazione completa (per footer)
  const FullPaginationComponent = () => {
    if (totalPages <= 1) return null;

    const pages = [];
    const maxVisiblePages = 5;
    
    let startPage = Math.max(1, currentPage - Math.floor(maxVisiblePages / 2));
    let endPage = Math.min(totalPages, startPage + maxVisiblePages - 1);
    
    // Aggiusta se siamo vicini alla fine
    if (endPage - startPage + 1 < maxVisiblePages) {
      startPage = Math.max(1, endPage - maxVisiblePages + 1);
    }

    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }

    return (
      <div className="d-flex justify-content-center align-items-center">
        <CPagination>
          <CPaginationItem
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(1)}
          >
            ««
          </CPaginationItem>
          <CPaginationItem
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(currentPage - 1)}
          >
            ‹
          </CPaginationItem>
          
          {startPage > 1 && (
            <>
              <CPaginationItem onClick={() => setCurrentPage(1)}>1</CPaginationItem>
              {startPage > 2 && <CPaginationItem disabled>...</CPaginationItem>}
            </>
          )}
          
          {pages.map(page => (
            <CPaginationItem
              key={page}
              active={page === currentPage}
              onClick={() => setCurrentPage(page)}
            >
              {page}
            </CPaginationItem>
          ))}
          
          {endPage < totalPages && (
            <>
              {endPage < totalPages - 1 && <CPaginationItem disabled>...</CPaginationItem>}
              <CPaginationItem onClick={() => setCurrentPage(totalPages)}>
                {totalPages}
              </CPaginationItem>
            </>
          )}
          
          <CPaginationItem
            disabled={currentPage === totalPages}
            onClick={() => setCurrentPage(currentPage + 1)}
          >
            ›
          </CPaginationItem>
          <CPaginationItem
            disabled={currentPage === totalPages}
            onClick={() => setCurrentPage(totalPages)}
          >
            »»
          </CPaginationItem>
        </CPagination>
      </div>
    );
  };

  // Drag & Drop handlers
  const [draggedColumn, setDraggedColumn] = useState<number | null>(null);
  
  const handleDragStart = (e: React.DragEvent, index: number) => {
    setDraggedColumn(index);
    e.dataTransfer.effectAllowed = 'move';
  };
  
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  };
  
  const handleDrop = (e: React.DragEvent, dropIndex: number) => {
    e.preventDefault();
    if (draggedColumn !== null && draggedColumn !== dropIndex) {
      moveColumn(draggedColumn, dropIndex);
    }
    setDraggedColumn(null);
  };

  // Componente selettore colonne
  const ColumnSelectorComponent = () => (
    <CDropdown>
      <CDropdownToggle size="sm" color="secondary" variant="outline" className="d-flex align-items-center gap-1">
        <span>📋</span>
        <span>Colonne</span>
        <span className="badge bg-primary rounded-pill ms-1" style={{ fontSize: '0.7rem' }}>
          {visibleColumns.size}/{allColumns.length}
        </span>
      </CDropdownToggle>
      <CDropdownMenu 
        style={{ 
          maxHeight: '400px', 
          overflowY: 'auto',
          minWidth: '280px',
          boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
          border: '1px solid rgba(0,0,0,0.1)'
        }}
      >
        <div className="px-3 py-2 bg-light border-bottom">
          <div className="fw-bold text-dark mb-1" style={{ fontSize: '0.9rem' }}>
            Personalizza Colonne
          </div>
          <div className="small text-muted">
            Seleziona le colonne da visualizzare
          </div>
        </div>
        
        <div className="px-3 py-2 bg-info-subtle border-bottom">
          <div className="d-flex align-items-center gap-2">
            <span>💡</span>
            <span className="small text-info">
              Trascina gli header per riordinare
            </span>
          </div>
        </div>
        
        {/* Colonne definite manualmente */}
        {initialColumns.length > 0 && (
          <div className="border-bottom">
            <div className="px-3 py-2 bg-light">
              <div className="fw-bold small text-secondary">COLONNE PRINCIPALI</div>
            </div>
            <div className="py-1">
              {initialColumns.map(column => (
                <div key={String(column.key)} className="px-3 py-1 hover-bg-light column-selector-checkbox">
                  <CFormCheck
                    id={`col-${String(column.key)}`}
                    checked={visibleColumns.has(column.key)}
                    onChange={() => toggleColumn(column.key)}
                    label={column.label}
                    className="small text-dark"
                  />
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Colonne auto-generate */}
        {autoGeneratedColumns.length > 0 && (
          <div className="border-bottom">
            <div className="px-3 py-2 bg-light">
              <div className="fw-bold small text-secondary">CAMPI AGGIUNTIVI</div>
            </div>
            <div className="py-1">
              {autoGeneratedColumns.map(column => (
                <div key={String(column.key)} className="px-3 py-1 hover-bg-light column-selector-checkbox">
                  <CFormCheck
                    id={`col-auto-${String(column.key)}`}
                    checked={visibleColumns.has(column.key)}
                    onChange={() => toggleColumn(column.key)}
                    label={column.label}
                    className="small text-dark"
                  />
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Actions */}
        <div className="p-2">
          <div className="d-grid">
            <button
              className="btn btn-outline-secondary btn-sm d-flex align-items-center justify-content-center gap-2"
              onClick={() => {
                // Reset alle impostazioni default
                const defaultVisible = new Set<keyof T>();
                allColumns.forEach(col => {
                  if (col.defaultVisible !== false) {
                    defaultVisible.add(col.key);
                  }
                });
                setVisibleColumns(defaultVisible);
                setOrderedColumns(allColumns);
                saveColumnConfig(defaultVisible, allColumns);
              }}
            >
              <span>🔄</span>
              <span>Ripristina Default</span>
            </button>
          </div>
        </div>
        
        {/* Debug info in development */}
        {process.env.NODE_ENV === 'development' && (
          <>
            <div className="border-top p-2">
              <div className="d-grid gap-1">
                <button
                  className="btn btn-outline-info btn-sm d-flex align-items-center justify-content-center gap-2"
                  onClick={() => {
                    console.log('Current config in localStorage:', localStorage.getItem(`table-config-${tableId}`));
                    console.log('Current visible columns:', Array.from(visibleColumns));
                    console.log('Current column order:', orderedColumns.map(col => col.key));
                  }}
                >
                  <span>🐛</span>
                  <span>Debug Info</span>
                </button>
                <button
                  className="btn btn-outline-danger btn-sm d-flex align-items-center justify-content-center gap-2"
                  onClick={() => {
                    localStorage.removeItem(`table-config-${tableId}`);
                    window.location.reload();
                  }}
                >
                  <span>🗑️</span>
                  <span>Clear Config</span>
                </button>
              </div>
            </div>
          </>
        )}
      </CDropdownMenu>
    </CDropdown>
  );

  // Icona ordinamento
  const getSortIcon = (column: keyof T) => {
    const columnConfig = visibleColumnsData.find(col => col.key === column);
    if (!columnConfig?.sortable) return null;
    
    if (sortColumn !== column) return ' ↕️';
    if (sortDirection === 'asc') return ' ↑';
    if (sortDirection === 'desc') return ' ↓';
    return ' ↕️';
  };

  return (
    <div className={`data-table ${className}`}>
        {/* Header con ricerca, paginazione e controlli */}
      <div className="mb-3">
        <div className="row align-items-center">
          <div className="col-md-4">
            {searchable && (
              <CFormInput
                type="text"
                placeholder={searchPlaceholder}
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
            )}
          </div>
          
          <div className="col-md-4 d-flex justify-content-center">
            <CompactPaginationComponent />
          </div>
          
          <div className="col-md-4 d-flex justify-content-end gap-2">
            <ColumnSelectorComponent />
          </div>
        </div>
      </div>

      {/* Gestione errori */}
      {error && (
        <div className="alert alert-danger">
          {error}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="text-center py-4">
          <CSpinner color="primary" />
          <div className="mt-2">Caricamento...</div>
        </div>
      )}

      {/* Tabella */}
      {!loading && (
        <div className="table-responsive">
          <CTable striped hover>
            <CTableHead>
              <CTableRow>
                {visibleColumnsData.map((column, index) => {
                  const isActionsColumn = column.key === 'id' && column.label === 'Azioni';
                  const isLastColumn = index === visibleColumnsData.length - 1;
                  
                  return (
                    <CTableHeaderCell
                      key={String(column.key)}
                      draggable={!isActionsColumn}
                      onDragStart={!isActionsColumn ? (e) => handleDragStart(e, index) : undefined}
                      onDragOver={!isActionsColumn ? handleDragOver : undefined}
                      onDrop={!isActionsColumn ? (e) => handleDrop(e, index) : undefined}
                      style={{
                        width: isActionsColumn && !isLastColumn ? 'auto' : column.width,
                        cursor: column.sortable ? 'pointer' : 'default',
                        userSelect: 'none',
                        opacity: draggedColumn === index ? 0.5 : 1,
                        transition: 'opacity 0.2s ease',
                        position: 'relative',
                        ...(isActionsColumn ? { textAlign: 'right' } : {})
                      }}
                      onClick={() => column.sortable && handleSort(column.key)}
                      className={`${draggedColumn === index ? 'border border-primary' : ''} ${isActionsColumn ? 'text-end' : ''}`}
                    >
                      <div className={`d-flex align-items-center ${isActionsColumn ? 'justify-content-end' : ''}`}>
                        {!isActionsColumn && (
                          <span className="me-1" style={{ cursor: 'grab' }}>⋮⋮</span>
                        )}
                        <span>{column.label}</span>
                        {getSortIcon(column.key)}
                      </div>
                    </CTableHeaderCell>
                  );
                })}
              </CTableRow>
            </CTableHead>
            <CTableBody>
              {currentData.length === 0 ? (
                <CTableRow>
                  <CTableDataCell colSpan={visibleColumnsData.length} className="text-center py-4">
                    {searchTerm ? 'Nessun risultato trovato' : 'Nessun dato disponibile'}
                  </CTableDataCell>
                </CTableRow>
              ) : (
                currentData.map((item, index) => (
                  <CTableRow key={index}>
                    {visibleColumnsData.map((column) => {
                      const isActionsColumn = column.key === 'id' && column.label === 'Azioni';
                      
                      return (
                        <CTableDataCell 
                          key={String(column.key)}
                          className={isActionsColumn ? 'text-end' : ''}
                        >
                          {column.render 
                            ? column.render(item[column.key], item)
                            : String(item[column.key] ?? '-')
                          }
                        </CTableDataCell>
                      );
                    })}
                  </CTableRow>
                ))
              )}
            </CTableBody>
          </CTable>
        </div>
      )}

      {/* Paginazione inferiore */}
      {!loading && (
        <div className="mt-3">
          <FullPaginationComponent />
        </div>
      )}
    </div>
  );
};

export default DataTable;