import React, { useState, useMemo } from 'react';
import { 
  CTable, 
  CTableHead, 
  CTableRow, 
  CTableHeaderCell, 
  CTableBody, 
  CTableDataCell,
  CFormInput,
  CFormSelect,
  CPagination,
  CPaginationItem,
  CSpinner,
  CFormCheck
} from '@coreui/react';
import CIcon from '@coreui/icons-react';
import { cilArrowTop, cilArrowBottom, cilResizeWidth,cilArrowRightLeft,cilArrowCircleRight } from '@coreui/icons';
import './DataTable.css';

export interface DataTableColumn<T> {
  key: keyof T;
  label: string;
  sortable?: boolean;
  render?: (value: any, item: T) => React.ReactNode;
  width?: string;
  defaultVisible?: boolean;
  order?: number;
  align?: 'left' | 'center' | 'right' | 'auto';
}

interface DataTableProps<T> {
  data: T[];
  columns: DataTableColumn<T>[];
  loading?: boolean;
  error?: string | null;
  searchable?: boolean;
  searchPlaceholder?: string;
  pageSize?: number;
  pageSizeOptions?: number[];
  className?: string;
  tableId?: string;
  autoDetectColumns?: boolean;
}

type SortDirection = 'asc' | 'desc' | null;

const DataTable = <T extends Record<string, any>>({
  data,
  columns: initialColumns,
  loading = false,
  error = null,
  searchable = true,
  searchPlaceholder = "Cerca...",
  pageSize = 10,
  pageSizeOptions = [10, 20, 50, 100],
  className = "",
  tableId = "default-table",
  autoDetectColumns = false
}: DataTableProps<T>) => {

  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(pageSize);
  const [sortColumn, setSortColumn] = useState<keyof T | null>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>(null);

  // Auto-generate columns
  const autoGeneratedColumns = useMemo(() => {
    if (!autoDetectColumns || data.length === 0) return [];
    const firstItem = data[0];
    return Object.keys(firstItem).filter(k => !initialColumns.some(col => col.key === k))
      .map((key, idx) => ({
        key: key as keyof T,
        label: key.charAt(0).toUpperCase() + key.slice(1).replace(/_/g,' '),
        sortable: true,
        defaultVisible: false,
        order: 1000 + idx,
        render: (value: any) => {
          if (key.includes('data') && value) {
            try { return new Date(value).toLocaleDateString('it-IT'); } 
            catch { return String(value); }
          }
          return String(value ?? '-');
        }
      }));
  }, [data, initialColumns, autoDetectColumns]);

  const allColumns = useMemo(() => [...initialColumns, ...autoGeneratedColumns].sort((a,b)=> (a.order??100)-(b.order??100)), [initialColumns, autoGeneratedColumns]);

  const [visibleColumns, setVisibleColumns] = useState<Set<keyof T>>(() => {
    const defaultVisible = new Set<keyof T>();
    allColumns.forEach(col => { if (col.defaultVisible !== false) defaultVisible.add(col.key); });
    return defaultVisible;
  });
  const [orderedColumns, setOrderedColumns] = useState<DataTableColumn<T>[]>(allColumns);

  // Resize columns
  const [columnWidths, setColumnWidths] = useState<Map<keyof T, number>>(new Map());
  const [isResizing, setIsResizing] = useState(false);
  const [resizeColumn, setResizeColumn] = useState<keyof T | null>(null);
  const [resizeStartX, setResizeStartX] = useState(0);
  const [resizeStartWidth, setResizeStartWidth] = useState(0);
  const [justResized, setJustResized] = useState(false);

  const handleResizeStart = (e: React.MouseEvent, columnKey: keyof T) => {
    e.preventDefault(); e.stopPropagation();
    const currentWidth = columnWidths.get(columnKey) || 150;
    setIsResizing(true);
    setResizeColumn(columnKey);
    setResizeStartX(e.clientX);
    setResizeStartWidth(currentWidth);
    document.body.classList.add('resizing');
    document.addEventListener('mousemove', handleResizeMove);
    document.addEventListener('mouseup', handleResizeEnd);
  };

  const handleResizeMove = (e: MouseEvent) => {
    if (!isResizing || !resizeColumn) return;
    const deltaX = e.clientX - resizeStartX;
    const newWidth = Math.max(50, resizeStartWidth + deltaX);
    const newWidths = new Map(columnWidths);
    newWidths.set(resizeColumn, newWidth);
    setColumnWidths(newWidths);
  };

  const handleResizeEnd = () => {
    if (isResizing && resizeColumn) setJustResized(true);
    setTimeout(() => setJustResized(false),100);
    setIsResizing(false); setResizeColumn(null); setResizeStartX(0); setResizeStartWidth(0);
    document.body.classList.remove('resizing');
    document.removeEventListener('mousemove', handleResizeMove);
    document.removeEventListener('mouseup', handleResizeEnd);
  };

  // Sorting
  const handleSort = (column: keyof T) => {
    const col = orderedColumns.find(c=>c.key===column);
    if (!col?.sortable) return;
    if (sortColumn===column) {
      if (sortDirection==='asc') setSortDirection('desc');
      else if (sortDirection==='desc') { setSortDirection(null); setSortColumn(null); }
    } else { setSortColumn(column); setSortDirection('asc'); }
  };

  const getSortIcon = (column: keyof T) => {
    const col = orderedColumns.find(c=>c.key===column);
    if (!col?.sortable) return null;
    if (sortColumn !== column) return <CIcon icon={cilResizeWidth} />;
    if (sortDirection==='asc') return <CIcon icon={cilArrowTop} />;
    if (sortDirection==='desc') return <CIcon icon={cilArrowBottom} />;
    return <CIcon icon={cilResizeWidth} />;
  };

  // Filter & sort data
  const visibleColumnsData = orderedColumns.filter(c=>visibleColumns.has(c.key));

  const filteredData = useMemo(()=> {
    if (!searchTerm.trim()) return data;
    const s = searchTerm.toLowerCase();
    return data.filter(item => visibleColumnsData.some(col => {
      const val = item[col.key]; if (val==null) return false;
      return String(val).toLowerCase().includes(s);
    }));
  }, [data, searchTerm, visibleColumnsData]);

  const sortedData = useMemo(()=> {
    if (!sortColumn || !sortDirection) return filteredData;
    return [...filteredData].sort((a,b)=>{
      const aVal = a[sortColumn], bVal = b[sortColumn];
      if(aVal==null && bVal==null) return 0;
      if(aVal==null) return sortDirection==='asc'?-1:1;
      if(bVal==null) return sortDirection==='asc'?1:-1;
      if(typeof aVal==='string' && typeof bVal==='string') return sortDirection==='asc'? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
      if(typeof aVal==='number' && typeof bVal==='number') return sortDirection==='asc'? aVal-bVal : bVal-aVal;
      return sortDirection==='asc'? String(aVal).localeCompare(String(bVal)) : String(bVal).localeCompare(String(aVal));
    });
  }, [filteredData, sortColumn, sortDirection]);

  // Pagination
  const totalItems = sortedData.length;
  const totalPages = Math.ceil(totalItems/itemsPerPage);
  const startIndex = (currentPage-1)*itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentData = sortedData.slice(startIndex,endIndex);

  React.useEffect(()=> setCurrentPage(1), [searchTerm, itemsPerPage]);

  return (
    <div className={`data-table ${className}`}>
      {searchable && (
        <div className="mb-3">
          <CFormInput 
            type="text" 
            placeholder={searchPlaceholder}
            value={searchTerm}
            onChange={e=>setSearchTerm(e.target.value)}
          />
        </div>
      )}

      {loading && (
        <div className="text-center py-4">
          <CSpinner color="primary" />
        </div>
      )}

      {error && <div className="alert alert-danger">{error}</div>}

      {!loading && (
        <div className="table-responsive">
          <CTable striped hover style={{tableLayout:'fixed'}}>
            <CTableHead>
              <CTableRow>
                {visibleColumnsData.map((col,index)=> {
                  return (
                    <CTableHeaderCell
                      key={String(col.key)}
                      style={{width: columnWidths.get(col.key) || 'auto', cursor: col.sortable?'pointer':'default'}}
                      onClick={()=>handleSort(col.key)}
                    >
                      <div style={{display:'flex', alignItems:'center', justifyContent:'space-between'}}>
                        <span>{col.label}</span>
                        <span>{getSortIcon(col.key)}</span>
                      </div>
                      <div 
                        className="resize-handle" 
                        onMouseDown={e=>handleResizeStart(e,col.key)}
                      />
                    </CTableHeaderCell>
                  );
                })}
              </CTableRow>
            </CTableHead>
            <CTableBody>
              {currentData.map((item,rowIdx)=> (
                <CTableRow key={rowIdx}>
                  {visibleColumnsData.map(col=> (
                    <CTableDataCell key={String(col.key)}>
                      {col.render ? col.render(item[col.key], item) : String(item[col.key] ?? '-')}
                    </CTableDataCell>
                  ))}
                </CTableRow>
              ))}
              {currentData.length===0 && (
                <CTableRow>
                  <CTableDataCell colSpan={visibleColumnsData.length} className="text-center">
                    Nessun dato disponibile
                  </CTableDataCell>
                </CTableRow>
              )}
            </CTableBody>
          </CTable>

          {/* Paginazione inferiore */}
          {!loading && (
            <div className='mt-3 d-flex justify-content-end'>
              <CPagination aria-label="Page navigation example">
                {Array.from({length: totalPages}, (_,i)=>(
                  <CPaginationItem
                    key={i}
                    active={currentPage===i+1}
                    onClick={()=>setCurrentPage(i+1)}
                  >
                    {i+1}
                  </CPaginationItem>
                ))}
              </CPagination>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default DataTable;
