import React, { useState, useMemo } from 'react';
import { 
  CTable, 
  CTableHead, 
  CTableRow, 
  CTableHeaderCell, 
  CTableBody, 
  CTableDataCell,
  CFormInput,
  CFormSelect,
  CPagination,
  CPaginationItem,
  CSpinner,
  CDropdown,
  CDropdownToggle,
  CDropdownMenu,
  CDropdownItem,
  CFormCheck
} from '@coreui/react';

import './DataTable.css';

export interface DataTableColumn<T> {
  key: keyof T;
  label: string;
  sortable?: boolean;
  render?: (value: any, item: T) => React.ReactNode;
  width?: string;
  defaultVisible?: boolean; // Colonna visibile di default
  order?: number; // Ordine di visualizzazione
  align?: 'left' | 'center' | 'right' | 'auto'; // Allineamento colonna
}

interface DataTableProps<T> {
  data: T[];
  columns: DataTableColumn<T>[];
  loading?: boolean;
  error?: string | null;
  searchable?: boolean;
  searchPlaceholder?: string;
  pageSize?: number;
  pageSizeOptions?: number[];
  className?: string;
  tableId?: string; // ID univoco per salvare configurazione colonne
  autoDetectColumns?: boolean; // Auto-genera colonne da dati
}

type SortDirection = 'asc' | 'desc' | null;

const DataTable = <T extends Record<string, any>>({
  data,
  columns: initialColumns,
  loading = false,
  error = null,
  searchable = true,
  searchPlaceholder = "Cerca...",
  pageSize = 10,
  pageSizeOptions = [10, 20, 50, 100],
  className = "",
  tableId = "default-table",
  autoDetectColumns = false
}: DataTableProps<T>) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(pageSize);
  const [sortColumn, setSortColumn] = useState<keyof T | null>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>(null);
  
  // Auto-genera colonne se richiesto
  const autoGeneratedColumns = useMemo((): DataTableColumn<T>[] => {
    if (!autoDetectColumns || data.length === 0) return [];
    
    const firstItem = data[0];
    const detectedColumns: DataTableColumn<T>[] = [];
    
    Object.keys(firstItem).forEach((key, index) => {
      // Escludi colonne che sono già definite manualmente
      if (!initialColumns.some(col => col.key === key)) {
        detectedColumns.push({
          key: key as keyof T,
          label: key.charAt(0).toUpperCase() + key.slice(1).replace(/_/g, ' '),
          sortable: true,
          defaultVisible: false,
          order: 1000 + index, // Ordine alto per metterle in fondo
          render: (value) => {
            // Gestione speciale per date
            if (key.includes('data') && value) {
              try {
                return new Date(value).toLocaleDateString('it-IT');
              } catch {
                return String(value);
              }
            }
            return String(value ?? '-');
          }
        });
      }
    });
    
    return detectedColumns;
  }, [data, initialColumns, autoDetectColumns]);
  
  // Combina colonne manuali e auto-generate
  const allColumns = useMemo(() => {
    return [...initialColumns, ...autoGeneratedColumns].sort((a, b) => {
      const orderA = a.order ?? 100;
      const orderB = b.order ?? 100;
      return orderA - orderB;
    });
  }, [initialColumns, autoGeneratedColumns]);
  
  // Carica configurazione colonne salvata
  const loadColumnConfig = () => {
    if (!tableId) return { visible: new Set<keyof T>(), order: allColumns };
    
    try {
      const saved = localStorage.getItem(`table-config-${tableId}`);
      if (saved) {
        const config = JSON.parse(saved);
        const visibleSet = new Set<keyof T>(config.visibleColumns);
        
        
        // Ordina colonne secondo configurazione salvata
        const orderedColumns: DataTableColumn<T>[] = [];
        const unorderedColumns: DataTableColumn<T>[] = [];
        
        // Prima aggiungi le colonne nell'ordine salvato
        config.columnOrder.forEach((savedKey: string) => {
          const column = allColumns.find(col => String(col.key) === savedKey);
          if (column) {
            orderedColumns.push(column);
          }
        });
        
        // Poi aggiungi eventuali nuove colonne non presenti nell'ordine salvato
        allColumns.forEach(col => {
          if (!config.columnOrder.includes(String(col.key))) {
            unorderedColumns.push(col);
          }
        });
        
        const finalOrder = [...orderedColumns, ...unorderedColumns];
        
        return { visible: visibleSet, order: finalOrder };
      }
    } catch (error) {
      console.warn('Errore caricamento configurazione tabella:', error);
    }
    
    // Default: solo colonne con defaultVisible !== false
    const defaultVisible = new Set<keyof T>();
    allColumns.forEach(col => {
      if (col.defaultVisible !== false) {
        defaultVisible.add(col.key);
      }
    });
    
    return { visible: defaultVisible, order: allColumns };
  };
  
  // Salva configurazione colonne
  const saveColumnConfig = (visibleCols: Set<keyof T>, orderedCols: DataTableColumn<T>[]) => {
    if (!tableId) return;
    
    try {
      const config = {
        visibleColumns: Array.from(visibleCols),
        columnOrder: orderedCols.map(col => String(col.key))
      };
      localStorage.setItem(`table-config-${tableId}`, JSON.stringify(config));
    } catch (error) {
      console.warn('Errore salvataggio configurazione tabella:', error);
    }
  };
  
  // Stato configurazione colonne
  const [columnConfig, setColumnConfig] = useState(() => loadColumnConfig());
  const [visibleColumns, setVisibleColumns] = useState(columnConfig.visible);
  const [orderedColumns, setOrderedColumns] = useState(columnConfig.order);
  
  // Stato per resize colonne
  const [columnWidths, setColumnWidths] = useState<Map<keyof T, number>>(() => {
    const savedWidths = localStorage.getItem(`table-widths-${tableId}`);
    try {
      if (savedWidths) {
        const parsed = JSON.parse(savedWidths);
        return new Map(Object.entries(parsed));
      }
    } catch (error) {
      console.warn('Errore caricamento larghezze colonne:', error);
    }
    return new Map();
  });
  
  // Salva larghezze colonne
  const saveColumnWidths = (widths: Map<keyof T, number>) => {
    if (!tableId) return;
    
    try {
      const widthsObj = Object.fromEntries(widths);
      localStorage.setItem(`table-widths-${tableId}`, JSON.stringify(widthsObj));
    } catch (error) {
      console.warn('Errore salvataggio larghezze colonne:', error);
    }
  };
  
  // Stato per resize drag
  const [isResizing, setIsResizing] = useState(false);
  const [resizeColumn, setResizeColumn] = useState<keyof T | null>(null);
  const [resizeStartX, setResizeStartX] = useState(0);
  const [resizeStartWidth, setResizeStartWidth] = useState(0);
  
  // Aggiorna quando cambiano le colonne
  React.useEffect(() => {
    const newConfig = loadColumnConfig();
    setVisibleColumns(newConfig.visible);
    setOrderedColumns(newConfig.order);
  }, [allColumns.length, tableId]);

  const toggleColumn = (columnKey: keyof T) => {
    const newVisible = new Set(visibleColumns);
    if (newVisible.has(columnKey)) {
      newVisible.delete(columnKey);
    } else {
      newVisible.add(columnKey);
    }
    setVisibleColumns(newVisible);
    saveColumnConfig(newVisible, orderedColumns);
  };
  
  // Funzioni per resize colonne
  const handleResizeStart = (e: React.MouseEvent, columnKey: keyof T) => {
    e.preventDefault();
    e.stopPropagation();
    
    const currentWidth = columnWidths.get(columnKey) || 150; // Default width se non salvata
    
    setIsResizing(true);
    setResizeColumn(columnKey);
    setResizeStartX(e.clientX);
    setResizeStartWidth(currentWidth);
    
    // Aggiungi classe per disabilitare selezione
    document.body.classList.add('resizing');
    
    // Aggiungi event listeners globali
    document.addEventListener('mousemove', handleResizeMove);
    document.addEventListener('mouseup', handleResizeEnd);
  };
  
  const handleResizeMove = (e: MouseEvent) => {
    if (!isResizing || !resizeColumn) return;
    
    const deltaX = e.clientX - resizeStartX;
    const newWidth = Math.max(50, resizeStartWidth + deltaX); // Larghezza minima 50px
    
    const newWidths = new Map(columnWidths);
    newWidths.set(resizeColumn, newWidth);
    setColumnWidths(newWidths);
  };
  
  const handleResizeEnd = () => {
    if (isResizing && resizeColumn) {
      saveColumnWidths(columnWidths);
    }
    
    setIsResizing(false);
    setResizeColumn(null);
    setResizeStartX(0);
    setResizeStartWidth(0);
    
    // Rimuovi classe per riabilitare selezione
    document.body.classList.remove('resizing');
    
    // Rimuovi event listeners globali
    document.removeEventListener('mousemove', handleResizeMove);
    document.removeEventListener('mouseup', handleResizeEnd);
  };
  
  // Cleanup event listeners
  React.useEffect(() => {
    return () => {
      document.removeEventListener('mousemove', handleResizeMove);
      document.removeEventListener('mouseup', handleResizeEnd);
    };
  }, []);
  
  // Ottieni larghezza di una colonna
  const getColumnWidth = (column: DataTableColumn<T>) => {
    const savedWidth = columnWidths.get(column.key);
    if (savedWidth) return `${savedWidth}px`;
    return column.width || 'auto';
  };

  // Sposta colonna (drag & drop) - lavora con l'ordine completo delle colonne
  const moveColumn = (fromVisibleIndex: number, toVisibleIndex: number) => {
    const visibleCols = orderedColumns.filter(col => visibleColumns.has(col.key));
    const movedColumn = visibleCols[fromVisibleIndex];
    const targetColumn = visibleCols[toVisibleIndex];
    
    if (!movedColumn || !targetColumn) return;
    
    // Trova gli indici nel array completo delle colonne
    const fromFullIndex = orderedColumns.findIndex(col => col.key === movedColumn.key);
    const toFullIndex = orderedColumns.findIndex(col => col.key === targetColumn.key);
    
    if (fromFullIndex === -1 || toFullIndex === -1) return;
    
    // Crea nuovo ordine completo
    const newOrder = [...orderedColumns];
    const [removed] = newOrder.splice(fromFullIndex, 1);
    newOrder.splice(toFullIndex, 0, removed);
    
    setOrderedColumns(newOrder);
    saveColumnConfig(visibleColumns, newOrder);
  };

  // Filtra solo le colonne visibili
  const visibleColumnsData = orderedColumns.filter(col => visibleColumns.has(col.key));

  // Funzione per determinare l'allineamento automatico intelligente
  const getColumnAlignment = (column: DataTableColumn<T>, value: any): 'left' | 'center' | 'right' => {
    // Se è specificato manualmente, usa quello (tranne 'auto')
    if (column.align && column.align !== 'auto') {
      return column.align;
    }

    // Allineamento automatico intelligente
    const key = String(column.key).toLowerCase();
    
    // Date: centro
    if (key.includes('data') || key.includes('date') || key.includes('timestamp')) {
      return 'center';
    }
    
    // Se il valore è un numero, allinea a destra
    if (typeof value === 'number' && !isNaN(value)) {
      return 'right';
    }
    
    // Se il valore è una stringa che sembra un numero o valuta
    if (typeof value === 'string') {
      const stringValue = value.trim();
      
      // Controlla se è un numero (con possibili separatori)
      if (/^-?[\d,.]+(€|\$|%)?$/.test(stringValue) || 
          /^(€|\$)?\s?-?[\d,.]+(€|\$|%)?$/.test(stringValue)) {
        return 'right';
      }
      
      // Date in formato stringa
      if (/^\d{1,2}[\/\-\.]\d{1,2}[\/\-\.]\d{2,4}$/.test(stringValue) ||
          /^\d{4}[\/\-\.]\d{1,2}[\/\-\.]\d{1,2}$/.test(stringValue)) {
        return 'center';
      }
    }
    
    // Default: testo a sinistra
    return 'left';
  };

  // Filtra i dati in base alla ricerca
  const filteredData = useMemo(() => {
    if (!searchTerm.trim()) return data;
    
    const searchLower = searchTerm.toLowerCase().trim();
    return data.filter(item =>
      visibleColumnsData.some(column => {
        const value = item[column.key];
        if (value == null) return false;
        return String(value).toLowerCase().includes(searchLower);
      })
    );
  }, [data, searchTerm, visibleColumnsData]);

  // Ordina i dati
  const sortedData = useMemo(() => {
    if (!sortColumn || !sortDirection) return filteredData;

    return [...filteredData].sort((a, b) => {
      const aVal = a[sortColumn];
      const bVal = b[sortColumn];
      
      // Gestione valori null/undefined
      if (aVal == null && bVal == null) return 0;
      if (aVal == null) return sortDirection === 'asc' ? -1 : 1;
      if (bVal == null) return sortDirection === 'asc' ? 1 : -1;
      
      // Confronto valori
      let comparison = 0;
      if (typeof aVal === 'string' && typeof bVal === 'string') {
        comparison = aVal.localeCompare(bVal);
      } else if (typeof aVal === 'number' && typeof bVal === 'number') {
        comparison = aVal - bVal;
      } else {
        comparison = String(aVal).localeCompare(String(bVal));
      }
      
      return sortDirection === 'asc' ? comparison : -comparison;
    });
  }, [filteredData, sortColumn, sortDirection]);

  // Paginazione
  const totalItems = sortedData.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentData = sortedData.slice(startIndex, endIndex);

  // Gestione ordinamento
  const handleSort = (column: keyof T) => {
    const columnConfig = visibleColumnsData.find(col => col.key === column);
    if (!columnConfig?.sortable) return;

    if (sortColumn === column) {
      // Cicla: asc -> desc -> null
      if (sortDirection === 'asc') {
        setSortDirection('desc');
      } else if (sortDirection === 'desc') {
        setSortDirection(null);
        setSortColumn(null);
      }
    } else {
      setSortColumn(column);
      setSortDirection('asc');
    }
  };

  // Reset pagination quando cambiano filtri
  React.useEffect(() => {
    setCurrentPage(1);
  }, [searchTerm, itemsPerPage]);

  // Componente paginazione compatta (per header)
  const CompactPaginationComponent = () => {
    if (totalPages <= 1) return null;

    return (
      <div className="d-flex align-items-center gap-3">
        <div className="text-muted small">
          {startIndex + 1}-{Math.min(endIndex, totalItems)} di {totalItems}
        </div>
        
        <CPagination size="sm">
          <CPaginationItem
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(currentPage - 1)}
          >
            ‹
          </CPaginationItem>
          <CPaginationItem active>
            {currentPage}
          </CPaginationItem>
          <CPaginationItem
            disabled={currentPage === totalPages}
            onClick={() => setCurrentPage(currentPage + 1)}
          >
            ›
          </CPaginationItem>
        </CPagination>
        
        <div className="d-flex align-items-center gap-1">
          <span className="text-muted small">per pagina:</span>
          <CFormSelect
            size="sm"
            value={itemsPerPage}
            onChange={(e) => setItemsPerPage(Number(e.target.value))}
            style={{ width: '70px' }}
          >
            {pageSizeOptions.map(size => (
              <option key={size} value={size}>{size}</option>
            ))}
          </CFormSelect>
        </div>
      </div>
    );
  };

  // Componente paginazione completa (per footer)
  const FullPaginationComponent = () => {
    if (totalPages <= 1) return null;

    const pages = [];
    const maxVisiblePages = 5;
    
    let startPage = Math.max(1, currentPage - Math.floor(maxVisiblePages / 2));
    let endPage = Math.min(totalPages, startPage + maxVisiblePages - 1);
    
    // Aggiusta se siamo vicini alla fine
    if (endPage - startPage + 1 < maxVisiblePages) {
      startPage = Math.max(1, endPage - maxVisiblePages + 1);
    }

    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }

    return (
      <div className="d-flex justify-content-center align-items-center">
        <CPagination>
          <CPaginationItem
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(1)}
          >
            ««
          </CPaginationItem>
          <CPaginationItem
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(currentPage - 1)}
          >
            ‹
          </CPaginationItem>
          
          {startPage > 1 && (
            <>
              <CPaginationItem onClick={() => setCurrentPage(1)}>1</CPaginationItem>
              {startPage > 2 && <CPaginationItem disabled>...</CPaginationItem>}
            </>
          )}
          
          {pages.map(page => (
            <CPaginationItem
              key={page}
              active={page === currentPage}
              onClick={() => setCurrentPage(page)}
            >
              {page}
            </CPaginationItem>
          ))}
          
          {endPage < totalPages && (
            <>
              {endPage < totalPages - 1 && <CPaginationItem disabled>...</CPaginationItem>}
              <CPaginationItem onClick={() => setCurrentPage(totalPages)}>
                {totalPages}
              </CPaginationItem>
            </>
          )}
          
          <CPaginationItem
            disabled={currentPage === totalPages}
            onClick={() => setCurrentPage(currentPage + 1)}
          >
            ›
          </CPaginationItem>
          <CPaginationItem
            disabled={currentPage === totalPages}
            onClick={() => setCurrentPage(totalPages)}
          >
            »»
          </CPaginationItem>
        </CPagination>
      </div>
    );
  };

  // Drag & Drop handlers
  const [draggedColumn, setDraggedColumn] = useState<number | null>(null);
  
  // Stato per controllare l'apertura del dropdown colonne
  const [columnSelectorOpen, setColumnSelectorOpen] = useState(false);
  
  // Chiudi dropdown quando si clicca fuori o si preme ESC
  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      const target = event.target as Element;
      const columnSelector = target?.closest('.column-selector-wrapper');
      
      if (!columnSelector && columnSelectorOpen) {
        setColumnSelectorOpen(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && columnSelectorOpen) {
        setColumnSelectorOpen(false);
      }
    };

    if (columnSelectorOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      document.addEventListener('keydown', handleKeyDown);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [columnSelectorOpen]);
  
  const handleDragStart = (e: React.DragEvent, index: number) => {
    setDraggedColumn(index);
    e.dataTransfer.effectAllowed = 'move';
  };
  
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  };
  
  const handleDrop = (e: React.DragEvent, dropIndex: number) => {
    e.preventDefault();
    if (draggedColumn !== null && draggedColumn !== dropIndex) {
      moveColumn(draggedColumn, dropIndex);
    }
    setDraggedColumn(null);
  };

  // Componente selettore colonne custom
  const ColumnSelectorComponent = () => (
    <div className="position-relative column-selector-wrapper">
      <button 
        type="button"
        className="btn btn-outline-secondary btn-sm d-flex align-items-center gap-1"
        onClick={() => setColumnSelectorOpen(!columnSelectorOpen)}
        style={{ border: '1px solid #6c757d' }}
      >
        <span>📋</span>
        <span>Colonne</span>
        <span className="badge bg-primary rounded-pill ms-1" style={{ fontSize: '0.7rem' }}>
          {visibleColumns.size}/{allColumns.length}
        </span>
        <span 
          className="ms-1" 
          style={{ 
            fontSize: '0.7rem',
            transform: columnSelectorOpen ? 'rotate(180deg)' : 'rotate(0deg)',
            transition: 'transform 0.2s ease'
          }}
        >
          ▼
        </span>
      </button>
      
      {columnSelectorOpen && (
        <div 
          className="position-absolute bg-white border rounded shadow-lg column-selector-dropdown"
          style={{ 
            top: '100%', 
            right: '0',
            zIndex: 1050,
            maxHeight: '400px', 
            overflowY: 'auto',
            minWidth: '280px',
            marginTop: '4px'
          }}
        >
        <div className="px-3 py-2 bg-light border-bottom">
          <div className="fw-bold text-dark mb-1" style={{ fontSize: '0.9rem' }}>
            Personalizza Colonne
          </div>
          <div className="small text-muted">
            Seleziona le colonne da visualizzare
          </div>
        </div>
        
        <div className="px-3 py-2 bg-info-subtle border-bottom">
          <div className="d-flex align-items-center gap-2">
            <span>💡</span>
            <span className="small text-info">
              Trascina gli header per riordinare
            </span>
          </div>
        </div>
        
        {/* Colonne definite manualmente */}
        {initialColumns.length > 0 && (
          <div className="border-bottom">
            <div className="px-3 py-2 bg-light">
              <div className="fw-bold small text-secondary">COLONNE PRINCIPALI</div>
            </div>
            <div className="py-1">
              {initialColumns.map(column => (
                <div 
                  key={String(column.key)} 
                  className="px-3 py-1 hover-bg-light column-selector-checkbox"
                >
                  <CFormCheck
                    id={`col-${String(column.key)}`}
                    checked={visibleColumns.has(column.key)}
                    onChange={(e) => {
                      e.stopPropagation();
                      toggleColumn(column.key);
                    }}
                    label={column.label}
                    className="small text-dark"
                  />
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Colonne auto-generate */}
        {autoGeneratedColumns.length > 0 && (
          <div className="border-bottom">
            <div className="px-3 py-2 bg-light">
              <div className="fw-bold small text-secondary">CAMPI AGGIUNTIVI</div>
            </div>
            <div className="py-1">
              {autoGeneratedColumns.map(column => (
                <div 
                  key={String(column.key)} 
                  className="px-3 py-1 hover-bg-light column-selector-checkbox"
                >
                  <CFormCheck
                    id={`col-auto-${String(column.key)}`}
                    checked={visibleColumns.has(column.key)}
                    onChange={(e) => {
                      e.stopPropagation();
                      toggleColumn(column.key);
                    }}
                    label={column.label}
                    className="small text-dark"
                  />
                </div>
              ))}
            </div>
          </div>
        )}
        
        {/* Actions */}
        <div className="p-2">
          <div className="d-grid">
            <button
              className="btn btn-outline-secondary btn-sm d-flex align-items-center justify-content-center gap-2"
              onClick={(e) => {
                e.stopPropagation();
                // Reset alle impostazioni default
                const defaultVisible = new Set<keyof T>();
                allColumns.forEach(col => {
                  if (col.defaultVisible !== false) {
                    defaultVisible.add(col.key);
                  }
                });
                setVisibleColumns(defaultVisible);
                setOrderedColumns(allColumns);
                saveColumnConfig(defaultVisible, allColumns);
              }}
            >
              <span>🔄</span>
              <span>Ripristina Default</span>
            </button>
          </div>
        </div>
        
        {/* Debug info in development */}
        {process.env.NODE_ENV === 'development' && (
          <>
            <div className="border-top p-2">
              <div className="d-grid gap-1">
                <button
                  className="btn btn-outline-info btn-sm d-flex align-items-center justify-content-center gap-2"
                  onClick={() => {
                    console.log('Current config in localStorage:', localStorage.getItem(`table-config-${tableId}`));
                    console.log('Current visible columns:', Array.from(visibleColumns));
                    console.log('Current column order:', orderedColumns.map(col => col.key));
                  }}
                >
                  <span>🐛</span>
                  <span>Debug Info</span>
                </button>
                <button
                  className="btn btn-outline-danger btn-sm d-flex align-items-center justify-content-center gap-2"
                  onClick={() => {
                    localStorage.removeItem(`table-config-${tableId}`);
                    window.location.reload();
                  }}
                >
                  <span>🗑️</span>
                  <span>Clear Config</span>
                </button>
              </div>
            </div>
          </>
        )}
        </div>
      )}
    </div>
  );

  // Icona ordinamento
  const getSortIcon = (column: keyof T) => {
    const columnConfig = visibleColumnsData.find(col => col.key === column);
    if (!columnConfig?.sortable) return null;
    
    if (sortColumn !== column) return ' ↕️';
    if (sortDirection === 'asc') return ' ↑';
    if (sortDirection === 'desc') return ' ↓';
    return ' ↕️';
  };

  return (
    <div className={`data-table ${className}`}>
        {/* Header con ricerca, paginazione e controlli */}
      <div className="mb-3">
        <div className="row align-items-center">
          <div className="col-md-4">
            {searchable && (
              <div className="position-relative">
                <CFormInput
                  type="text"
                  placeholder={searchPlaceholder}
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  style={searchTerm ? { paddingRight: '35px' } : {}}
                />
                {searchTerm && (
                  <button
                    type="button"
                    className="btn btn-link position-absolute top-50 translate-middle-y p-0"
                    style={{ 
                      right: '8px', 
                      zIndex: 10,
                      width: '20px',
                      height: '20px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: '12px',
                      color: '#6c757d',
                      textDecoration: 'none'
                    }}
                    onClick={() => setSearchTerm('')}
                    onMouseDown={(e) => e.preventDefault()}
                    title="Cancella ricerca"
                  >
                    ✕
                  </button>
                )}
              </div>
            )}
          </div>
          
          <div className="col-md-4 d-flex justify-content-center">
            <CompactPaginationComponent />
          </div>
          
          <div className="col-md-4 d-flex justify-content-end gap-2">
            <ColumnSelectorComponent />
          </div>
        </div>
      </div>

      {/* Gestione errori */}
      {error && (
        <div className="alert alert-danger">
          {error}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="text-center py-4">
          <CSpinner color="primary" />
          <div className="mt-2">Caricamento...</div>
        </div>
      )}

      {/* Tabella */}
      {!loading && (
        <div className="table-responsive">
          <CTable striped hover>
            <CTableHead>
              <CTableRow>
                {visibleColumnsData.map((column, index) => {
                  const isActionsColumn = column.key === 'id' && column.label === 'Azioni';
                  const isLastColumn = index === visibleColumnsData.length - 1;
                  
                  // Determina l'allineamento dell'header basato sulla colonna
                  let headerAlign = 'left';
                  if (isActionsColumn) {
                    headerAlign = 'right';
                  } else if (column.align && column.align !== 'auto') {
                    headerAlign = column.align;
                  } else {
                    // Per l'header, usa il primo valore disponibile per determinare l'allineamento
                    const firstValue = currentData.length > 0 ? currentData[0][column.key] : null;
                    headerAlign = getColumnAlignment(column, firstValue);
                  }
                  
                  return (
                    <CTableHeaderCell
                      key={String(column.key)}
                      draggable={!isActionsColumn}
                      onDragStart={!isActionsColumn ? (e) => handleDragStart(e, index) : undefined}
                      onDragOver={!isActionsColumn ? handleDragOver : undefined}
                      onDrop={!isActionsColumn ? (e) => handleDrop(e, index) : undefined}
                      style={{
                        width: isActionsColumn && !isLastColumn ? 'auto' : getColumnWidth(column),
                        cursor: column.sortable ? 'pointer' : 'default',
                        userSelect: 'none',
                        opacity: draggedColumn === index ? 0.5 : 1,
                        position: 'relative',
                        transition: 'opacity 0.2s ease',
                        textAlign: headerAlign as any
                      }}
                      onClick={() => column.sortable && handleSort(column.key)}
                      className={`${draggedColumn === index ? 'border border-primary' : ''} text-${headerAlign === 'left' ? 'start' : headerAlign === 'right' ? 'end' : 'center'}`}
                    >
                      <div className={`d-flex align-items-center ${
                        headerAlign === 'right' ? 'justify-content-end' : 
                        headerAlign === 'center' ? 'justify-content-center' : 
                        'justify-content-start'
                      }`}>
                        {!isActionsColumn && (
                          <span className="me-1" style={{ cursor: 'grab' }}>⋮⋮</span>
                        )}
                        <span>{column.label}</span>
                        {getSortIcon(column.key)}
                      </div>
                      
                      {/* Resize handle */}
                      {!isActionsColumn && (
                        <div
                          className="resize-handle"
                          onMouseDown={(e) => handleResizeStart(e, column.key)}
                          style={{
                            position: 'absolute',
                            right: 0,
                            top: 0,
                            bottom: 0,
                            width: '4px',
                            cursor: 'col-resize',
                            backgroundColor: 'transparent',
                            zIndex: 10,
                          }}
                          onMouseEnter={(e) => {
                            (e.target as HTMLElement).style.backgroundColor = 'rgba(0, 123, 255, 0.3)';
                          }}
                          onMouseLeave={(e) => {
                            (e.target as HTMLElement).style.backgroundColor = 'transparent';
                          }}
                        />
                      )}
                    </CTableHeaderCell>
                  );
                })}
              </CTableRow>
            </CTableHead>
            <CTableBody>
              {currentData.length === 0 ? (
                <CTableRow>
                  <CTableDataCell colSpan={visibleColumnsData.length} className="text-center py-4">
                    {searchTerm ? 'Nessun risultato trovato' : 'Nessun dato disponibile'}
                  </CTableDataCell>
                </CTableRow>
              ) : (
                currentData.map((item, index) => (
                  <CTableRow key={index}>
                    {visibleColumnsData.map((column) => {
                      const isActionsColumn = column.key === 'id' && column.label === 'Azioni';
                      const cellValue = item[column.key];
                      
                      // Determina l'allineamento della cella
                      let cellAlign = 'left';
                      if (isActionsColumn) {
                        cellAlign = 'right';
                      } else {
                        cellAlign = getColumnAlignment(column, cellValue);
                      }
                      
                      return (
                        <CTableDataCell 
                          key={String(column.key)}
                          className={`text-${cellAlign === 'left' ? 'start' : cellAlign === 'right' ? 'end' : 'center'}`}
                          style={{ textAlign: cellAlign as any }}
                        >
                          {column.render 
                            ? column.render(cellValue, item)
                            : String(cellValue ?? '-')
                          }
                        </CTableDataCell>
                      );
                    })}
                  </CTableRow>
                ))
              )}
            </CTableBody>
          </CTable>
        </div>
      )}

      {/* Paginazione inferiore */}
      {!loading && (
        <div className="mt-3">
          <FullPaginationComponent />
        </div>
      )}
    </div>
  );
};

export default DataTable;